reggie:
  redis:
    database: 0
    host: 192.168.127.131
    port: 6379
    password: 123456
  server:
    port: 8888
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://192.168.127.131:3306/reggie?serverTimezone=Asia/Shanghai
      &useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      &useSSL=false&allowPublicKeyRetrieval=true"
    username: yuxia
    password: 123456
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    bucket-name: sky-take-out-0011