version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: reggie
    volumes:
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/conf:/etc/mysql/conf.d
      - /root/mysql/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone/timezone:/etc/timezone:ro
    networks:
      - reggie-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    environment:
      - REDIS_PORT=6379
    volumes:
      - /root/redis/data:/data
      - /root/redis/conf:/usr/local/etc/redis
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone/timezone:/etc/timezone:ro
    networks:
      - reggie-network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  reggie-app:
    build: .
    container_name: reggie-app
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reggie?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone/timezone:/etc/timezone:ro
    networks:
      - reggie-network

  nginx:
    image: nginx:1.20.1
    container_name: nginx
    volumes:
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone/timezone:/etc/timezone:ro
    ports:
      - "18080:18080"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - reggie-app
    networks:
      - reggie-network

networks:
  reggie-network:
    driver: bridge
